"""Initial migration with all models

Revision ID: 01751e5d82a0
Revises: 
Create Date: 2026-01-20 17:11:51.721375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01751e5d82a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_entities_id'), 'test_entities', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_channel', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_user_id'), 'brands', ['user_id'], unique=False)
    op.create_table('collaborations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('deliverables_text', sa.Text(), nullable=True),
    sa.Column('agreed_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('deadline_date', sa.Date(), nullable=True),
    sa.Column('posting_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('LEAD', 'NEGOTIATING', 'CONFIRMED', 'IN_PRODUCTION', 'POSTED', 'PAYMENT_PENDING', 'OVERDUE', 'PAID', 'CLOSED', name='collaborationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaborations_brand_id'), 'collaborations', ['brand_id'], unique=False)
    op.create_index(op.f('ix_collaborations_id'), 'collaborations', ['id'], unique=False)
    op.create_index(op.f('ix_collaborations_user_id'), 'collaborations', ['user_id'], unique=False)
    op.create_table('conversation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collaboration_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'INSTAGRAM', 'WHATSAPP', 'PHONE', 'IN_PERSON', 'OTHER', name='communicationchannel'), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_logs_collaboration_id'), 'conversation_logs', ['collaboration_id'], unique=False)
    op.create_index(op.f('ix_conversation_logs_id'), 'conversation_logs', ['id'], unique=False)
    op.create_table('file_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collaboration_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_attachments_collaboration_id'), 'file_attachments', ['collaboration_id'], unique=False)
    op.create_index(op.f('ix_file_attachments_id'), 'file_attachments', ['id'], unique=False)
    op.create_table('payment_expectations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collaboration_id', sa.Integer(), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('promised_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARTIAL', 'COMPLETED', 'OVERDUE', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_expectations_collaboration_id'), 'payment_expectations', ['collaboration_id'], unique=False)
    op.create_index(op.f('ix_payment_expectations_id'), 'payment_expectations', ['id'], unique=False)
    op.create_table('payment_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_expectation_id', sa.Integer(), nullable=False),
    sa.Column('credited_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('credited_date', sa.Date(), nullable=False),
    sa.Column('reference_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['payment_expectation_id'], ['payment_expectations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_credits_id'), 'payment_credits', ['id'], unique=False)
    op.create_index(op.f('ix_payment_credits_payment_expectation_id'), 'payment_credits', ['payment_expectation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_credits_payment_expectation_id'), table_name='payment_credits')
    op.drop_index(op.f('ix_payment_credits_id'), table_name='payment_credits')
    op.drop_table('payment_credits')
    op.drop_index(op.f('ix_payment_expectations_id'), table_name='payment_expectations')
    op.drop_index(op.f('ix_payment_expectations_collaboration_id'), table_name='payment_expectations')
    op.drop_table('payment_expectations')
    op.drop_index(op.f('ix_file_attachments_id'), table_name='file_attachments')
    op.drop_index(op.f('ix_file_attachments_collaboration_id'), table_name='file_attachments')
    op.drop_table('file_attachments')
    op.drop_index(op.f('ix_conversation_logs_id'), table_name='conversation_logs')
    op.drop_index(op.f('ix_conversation_logs_collaboration_id'), table_name='conversation_logs')
    op.drop_table('conversation_logs')
    op.drop_index(op.f('ix_collaborations_user_id'), table_name='collaborations')
    op.drop_index(op.f('ix_collaborations_id'), table_name='collaborations')
    op.drop_index(op.f('ix_collaborations_brand_id'), table_name='collaborations')
    op.drop_table('collaborations')
    op.drop_index(op.f('ix_brands_user_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_test_entities_id'), table_name='test_entities')
    op.drop_table('test_entities')
    # ### end Alembic commands ###